[package]
name = "testokplain"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = { version = "1.0.0-alpha.17" }
serde_json = "1.0.139"
okapi = { git = "https://github.com/near/near-okapi-fork.git", features = ["schemars-alpha"] } # OpenAPI generation
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_with = { version = "3.0", features = ["base64"] }

[features]
progenitor = []
