[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
keeper = { path = "../keeper" }
reqwest = "0.12.12"
serde = "1.0.218"
serde_json = "1.0.139"
tokio = { version = "1", features = ["full"] }