/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessKeyPermissionViewOneOfFunctionCall {
    #[serde(rename = "allowance")]
    pub allowance: String,
    #[serde(rename = "receiver_id")]
    pub receiver_id: String,
    #[serde(rename = "method_names")]
    pub method_names: Vec<String>,
}

impl AccessKeyPermissionViewOneOfFunctionCall {
    pub fn new(allowance: String, receiver_id: String, method_names: Vec<String>) -> AccessKeyPermissionViewOneOfFunctionCall {
        AccessKeyPermissionViewOneOfFunctionCall {
            allowance,
            receiver_id,
            method_names,
        }
    }
}

