/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf7 : The length of the arguments exceeded the limit in a Function Call action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf7 {
    #[serde(rename = "FunctionCallArgumentsLengthExceeded")]
    pub function_call_arguments_length_exceeded: Box<models::HostErrorOneOf9KeyLengthExceeded>,
}

impl ActionsValidationErrorOneOf7 {
    /// The length of the arguments exceeded the limit in a Function Call action.
    pub fn new(function_call_arguments_length_exceeded: models::HostErrorOneOf9KeyLengthExceeded) -> ActionsValidationErrorOneOf7 {
        ActionsValidationErrorOneOf7 {
            function_call_arguments_length_exceeded: Box::new(function_call_arguments_length_exceeded),
        }
    }
}

