/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf19DelegateActionNonceTooLarge {
    #[serde(rename = "delegate_nonce")]
    pub delegate_nonce: i32,
    #[serde(rename = "upper_bound")]
    pub upper_bound: i32,
}

impl ActionErrorKindOneOf19DelegateActionNonceTooLarge {
    pub fn new(delegate_nonce: i32, upper_bound: i32) -> ActionErrorKindOneOf19DelegateActionNonceTooLarge {
        ActionErrorKindOneOf19DelegateActionNonceTooLarge {
            delegate_nonce,
            upper_bound,
        }
    }
}

