/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf10UseGlobalContract {
    #[serde(rename = "code_hash")]
    pub code_hash: String,
}

impl ActionViewOneOf10UseGlobalContract {
    pub fn new(code_hash: String) -> ActionViewOneOf10UseGlobalContract {
        ActionViewOneOf10UseGlobalContract {
            code_hash,
        }
    }
}

