/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf8 : ActionReceipt can't be completed, because the remaining balance will not be enough to cover storage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf8 {
    #[serde(rename = "LackBalanceForState")]
    pub lack_balance_for_state: Box<models::ActionErrorKindOneOf8LackBalanceForState>,
}

impl ActionErrorKindOneOf8 {
    /// ActionReceipt can't be completed, because the remaining balance will not be enough to cover storage.
    pub fn new(lack_balance_for_state: models::ActionErrorKindOneOf8LackBalanceForState) -> ActionErrorKindOneOf8 {
        ActionErrorKindOneOf8 {
            lack_balance_for_state: Box::new(lack_balance_for_state),
        }
    }
}

