/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationError : Describes the error for validating a list of actions.
/// Describes the error for validating a list of actions.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionsValidationError {
    /// The delete action must be a final action in transaction
    String(String),
    ActionsValidationErrorOneOf(Box<models::ActionsValidationErrorOneOf>),
    ActionsValidationErrorOneOf1(Box<models::ActionsValidationErrorOneOf1>),
    ActionsValidationErrorOneOf2(Box<models::ActionsValidationErrorOneOf2>),
    ActionsValidationErrorOneOf3(Box<models::ActionsValidationErrorOneOf3>),
    /// Integer overflow during a compute.
    String(String),
    ActionsValidationErrorOneOf4(Box<models::ActionsValidationErrorOneOf4>),
    ActionsValidationErrorOneOf5(Box<models::ActionsValidationErrorOneOf5>),
    ActionsValidationErrorOneOf6(Box<models::ActionsValidationErrorOneOf6>),
    ActionsValidationErrorOneOf7(Box<models::ActionsValidationErrorOneOf7>),
    ActionsValidationErrorOneOf8(Box<models::ActionsValidationErrorOneOf8>),
    /// The attached amount of gas in a FunctionCall action has to be a positive number.
    String(String),
    /// There should be the only one DelegateAction
    String(String),
    ActionsValidationErrorOneOf9(Box<models::ActionsValidationErrorOneOf9>),
}

impl Default for ActionsValidationError {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

