/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf16 : Receiver of the transaction doesn't match Sender of the delegate action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf16 {
    #[serde(rename = "DelegateActionSenderDoesNotMatchTxReceiver")]
    pub delegate_action_sender_does_not_match_tx_receiver: Box<models::ActionErrorKindOneOf16DelegateActionSenderDoesNotMatchTxReceiver>,
}

impl ActionErrorKindOneOf16 {
    /// Receiver of the transaction doesn't match Sender of the delegate action
    pub fn new(delegate_action_sender_does_not_match_tx_receiver: models::ActionErrorKindOneOf16DelegateActionSenderDoesNotMatchTxReceiver) -> ActionErrorKindOneOf16 {
        ActionErrorKindOneOf16 {
            delegate_action_sender_does_not_match_tx_receiver: Box::new(delegate_action_sender_does_not_match_tx_receiver),
        }
    }
}

