/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf1 : Happens when TX receiver_id doesn't exist (but action is not Action::CreateAccount)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf1 {
    #[serde(rename = "AccountDoesNotExist")]
    pub account_does_not_exist: Box<models::ActionViewOneOf11UseGlobalContractByAccountId>,
}

impl ActionErrorKindOneOf1 {
    /// Happens when TX receiver_id doesn't exist (but action is not Action::CreateAccount)
    pub fn new(account_does_not_exist: models::ActionViewOneOf11UseGlobalContractByAccountId) -> ActionErrorKindOneOf1 {
        ActionErrorKindOneOf1 {
            account_does_not_exist: Box::new(account_does_not_exist),
        }
    }
}

