/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf1FunctionCall {
    #[serde(rename = "method_name")]
    pub method_name: String,
    #[serde(rename = "args")]
    pub args: String,
    #[serde(rename = "gas")]
    pub gas: i32,
    #[serde(rename = "deposit")]
    pub deposit: String,
}

impl ActionViewOneOf1FunctionCall {
    pub fn new(method_name: String, args: String, gas: i32, deposit: String) -> ActionViewOneOf1FunctionCall {
        ActionViewOneOf1FunctionCall {
            method_name,
            args,
            gas,
            deposit,
        }
    }
}

