/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionOneOf1 : Sets a Wasm code to a receiver_id
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOneOf1 {
    #[serde(rename = "DeployContract")]
    pub deploy_contract: Box<models::DeployContractAction>,
}

impl ActionOneOf1 {
    /// Sets a Wasm code to a receiver_id
    pub fn new(deploy_contract: models::DeployContractAction) -> ActionOneOf1 {
        ActionOneOf1 {
            deploy_contract: Box::new(deploy_contract),
        }
    }
}

