/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf1 : The number of actions exceeded the given limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf1 {
    #[serde(rename = "TotalNumberOfActionsExceeded")]
    pub total_number_of_actions_exceeded: Box<models::ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded>,
}

impl ActionsValidationErrorOneOf1 {
    /// The number of actions exceeded the given limit.
    pub fn new(total_number_of_actions_exceeded: models::ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded) -> ActionsValidationErrorOneOf1 {
        ActionsValidationErrorOneOf1 {
            total_number_of_actions_exceeded: Box::new(total_number_of_actions_exceeded),
        }
    }
}

