/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf18DelegateActionInvalidNonce {
    #[serde(rename = "delegate_nonce")]
    pub delegate_nonce: i32,
    #[serde(rename = "ak_nonce")]
    pub ak_nonce: i32,
}

impl ActionErrorKindOneOf18DelegateActionInvalidNonce {
    pub fn new(delegate_nonce: i32, ak_nonce: i32) -> ActionErrorKindOneOf18DelegateActionInvalidNonce {
        ActionErrorKindOneOf18DelegateActionInvalidNonce {
            delegate_nonce,
            ak_nonce,
        }
    }
}

