/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf9UnsupportedProtocolFeature {
    #[serde(rename = "protocol_feature")]
    pub protocol_feature: String,
    #[serde(rename = "version")]
    pub version: i32,
}

impl ActionsValidationErrorOneOf9UnsupportedProtocolFeature {
    pub fn new(protocol_feature: String, version: i32) -> ActionsValidationErrorOneOf9UnsupportedProtocolFeature {
        ActionsValidationErrorOneOf9UnsupportedProtocolFeature {
            protocol_feature,
            version,
        }
    }
}

