/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf3 : A newly created account must be under a namespace of the creator account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf3 {
    #[serde(rename = "CreateAccountNotAllowed")]
    pub create_account_not_allowed: Box<models::ActionErrorKindOneOf3CreateAccountNotAllowed>,
}

impl ActionErrorKindOneOf3 {
    /// A newly created account must be under a namespace of the creator account
    pub fn new(create_account_not_allowed: models::ActionErrorKindOneOf3CreateAccountNotAllowed) -> ActionErrorKindOneOf3 {
        ActionErrorKindOneOf3 {
            create_account_not_allowed: Box::new(create_account_not_allowed),
        }
    }
}

