/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionErrorKind {
    ActionErrorKindOneOf(Box<models::ActionErrorKindOneOf>),
    ActionErrorKindOneOf1(Box<models::ActionErrorKindOneOf1>),
    ActionErrorKindOneOf2(Box<models::ActionErrorKindOneOf2>),
    ActionErrorKindOneOf3(Box<models::ActionErrorKindOneOf3>),
    ActionErrorKindOneOf4(Box<models::ActionErrorKindOneOf4>),
    ActionErrorKindOneOf5(Box<models::ActionErrorKindOneOf5>),
    ActionErrorKindOneOf6(Box<models::ActionErrorKindOneOf6>),
    ActionErrorKindOneOf7(Box<models::ActionErrorKindOneOf7>),
    ActionErrorKindOneOf8(Box<models::ActionErrorKindOneOf8>),
    ActionErrorKindOneOf9(Box<models::ActionErrorKindOneOf9>),
    ActionErrorKindOneOf10(Box<models::ActionErrorKindOneOf10>),
    ActionErrorKindOneOf11(Box<models::ActionErrorKindOneOf11>),
    ActionErrorKindOneOf12(Box<models::ActionErrorKindOneOf12>),
    ActionErrorKindOneOf13(Box<models::ActionErrorKindOneOf13>),
    ActionErrorKindOneOf14(Box<models::ActionErrorKindOneOf14>),
    ActionErrorKindOneOf15(Box<models::ActionErrorKindOneOf15>),
    /// Signature does not match the provided actions and given signer public key.
    String(String),
    ActionErrorKindOneOf16(Box<models::ActionErrorKindOneOf16>),
    /// Delegate action has expired. `max_block_height` is less than actual block height.
    String(String),
    ActionErrorKindOneOf17(Box<models::ActionErrorKindOneOf17>),
    ActionErrorKindOneOf18(Box<models::ActionErrorKindOneOf18>),
    ActionErrorKindOneOf19(Box<models::ActionErrorKindOneOf19>),
    ActionErrorKindOneOf20(Box<models::ActionErrorKindOneOf20>),
}

impl Default for ActionErrorKind {
    fn default() -> Self {
        Self::ActionErrorKindOneOf(Default::default())
    }
}

