/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf6 {
    #[serde(rename = "DeleteAccount")]
    pub delete_account: Box<models::ActionViewOneOf6DeleteAccount>,
}

impl ActionViewOneOf6 {
    pub fn new(delete_account: models::ActionViewOneOf6DeleteAccount) -> ActionViewOneOf6 {
        ActionViewOneOf6 {
            delete_account: Box::new(delete_account),
        }
    }
}

