/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf13 : Error occurs when a new `ActionReceipt` created by the `FunctionCall` action fails receipt validation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf13 {
    #[serde(rename = "NewReceiptValidationError")]
    pub new_receipt_validation_error: Box<models::ReceiptValidationError>,
}

impl ActionErrorKindOneOf13 {
    /// Error occurs when a new `ActionReceipt` created by the `FunctionCall` action fails receipt validation.
    pub fn new(new_receipt_validation_error: models::ReceiptValidationError) -> ActionErrorKindOneOf13 {
        ActionErrorKindOneOf13 {
            new_receipt_validation_error: Box::new(new_receipt_validation_error),
        }
    }
}

