/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionOneOf : Create an (sub)account using a transaction `receiver_id` as an ID for a new account ID must pass validation rules described here <http://nomicon.io/Primitives/Account.html>.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOneOf {
    /// Create account action
    #[serde(rename = "CreateAccount")]
    pub create_account: serde_json::Value,
}

impl ActionOneOf {
    /// Create an (sub)account using a transaction `receiver_id` as an ID for a new account ID must pass validation rules described here <http://nomicon.io/Primitives/Account.html>.
    pub fn new(create_account: serde_json::Value) -> ActionOneOf {
        ActionOneOf {
            create_account,
        }
    }
}

