/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf20 {
    #[serde(rename = "GlobalContractDoesNotExist")]
    pub global_contract_does_not_exist: Box<models::ActionErrorKindOneOf20GlobalContractDoesNotExist>,
}

impl ActionErrorKindOneOf20 {
    pub fn new(global_contract_does_not_exist: models::ActionErrorKindOneOf20GlobalContractDoesNotExist) -> ActionErrorKindOneOf20 {
        ActionErrorKindOneOf20 {
            global_contract_does_not_exist: Box::new(global_contract_does_not_exist),
        }
    }
}

