/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOneOf6 {
    #[serde(rename = "DeleteKey")]
    pub delete_key: Box<models::DeleteKeyAction>,
}

impl ActionOneOf6 {
    pub fn new(delete_key: models::DeleteKeyAction) -> ActionOneOf6 {
        ActionOneOf6 {
            delete_key: Box::new(delete_key),
        }
    }
}

