/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf2 : A top-level account ID can only be created by registrar.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf2 {
    #[serde(rename = "CreateAccountOnlyByRegistrar")]
    pub create_account_only_by_registrar: Box<models::ActionErrorKindOneOf2CreateAccountOnlyByRegistrar>,
}

impl ActionErrorKindOneOf2 {
    /// A top-level account ID can only be created by registrar.
    pub fn new(create_account_only_by_registrar: models::ActionErrorKindOneOf2CreateAccountOnlyByRegistrar) -> ActionErrorKindOneOf2 {
        ActionErrorKindOneOf2 {
            create_account_only_by_registrar: Box::new(create_account_only_by_registrar),
        }
    }
}

