/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf2 : The total number of bytes of the method names exceeded the limit in a Add Key action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf2 {
    #[serde(rename = "AddKeyMethodNamesNumberOfBytesExceeded")]
    pub add_key_method_names_number_of_bytes_exceeded: Box<models::ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded>,
}

impl ActionsValidationErrorOneOf2 {
    /// The total number of bytes of the method names exceeded the limit in a Add Key action.
    pub fn new(add_key_method_names_number_of_bytes_exceeded: models::ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded) -> ActionsValidationErrorOneOf2 {
        ActionsValidationErrorOneOf2 {
            add_key_method_names_number_of_bytes_exceeded: Box::new(add_key_method_names_number_of_bytes_exceeded),
        }
    }
}

