/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOneOf7 {
    #[serde(rename = "DeleteAccount")]
    pub delete_account: Box<models::DeleteAccountAction>,
}

impl ActionOneOf7 {
    pub fn new(delete_account: models::DeleteAccountAction) -> ActionOneOf7 {
        ActionOneOf7 {
            delete_account: Box::new(delete_account),
        }
    }
}

