/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf : Happens when CreateAccount action tries to create an account with account_id which is already exists in the storage
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf {
    #[serde(rename = "AccountAlreadyExists")]
    pub account_already_exists: Box<models::ActionViewOneOf11UseGlobalContractByAccountId>,
}

impl ActionErrorKindOneOf {
    /// Happens when CreateAccount action tries to create an account with account_id which is already exists in the storage
    pub fn new(account_already_exists: models::ActionViewOneOf11UseGlobalContractByAccountId) -> ActionErrorKindOneOf {
        ActionErrorKindOneOf {
            account_already_exists: Box::new(account_already_exists),
        }
    }
}

