/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf3Stake {
    #[serde(rename = "stake")]
    pub stake: String,
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl ActionViewOneOf3Stake {
    pub fn new(stake: String, public_key: String) -> ActionViewOneOf3Stake {
        ActionViewOneOf3Stake {
            stake,
            public_key,
        }
    }
}

