/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf : The total prepaid gas (for all given actions) exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf {
    #[serde(rename = "TotalPrepaidGasExceeded")]
    pub total_prepaid_gas_exceeded: Box<models::ActionsValidationErrorOneOfTotalPrepaidGasExceeded>,
}

impl ActionsValidationErrorOneOf {
    /// The total prepaid gas (for all given actions) exceeded the limit.
    pub fn new(total_prepaid_gas_exceeded: models::ActionsValidationErrorOneOfTotalPrepaidGasExceeded) -> ActionsValidationErrorOneOf {
        ActionsValidationErrorOneOf {
            total_prepaid_gas_exceeded: Box::new(total_prepaid_gas_exceeded),
        }
    }
}

