/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf10 {
    #[serde(rename = "UseGlobalContract")]
    pub use_global_contract: Box<models::ActionViewOneOf10UseGlobalContract>,
}

impl ActionViewOneOf10 {
    pub fn new(use_global_contract: models::ActionViewOneOf10UseGlobalContract) -> ActionViewOneOf10 {
        ActionViewOneOf10 {
            use_global_contract: Box::new(use_global_contract),
        }
    }
}

