/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf8LackBalanceForState {
    /// An account which needs balance
    #[serde(rename = "account_id")]
    pub account_id: String,
    /// Balance required to complete an action.
    #[serde(rename = "amount")]
    pub amount: String,
}

impl ActionErrorKindOneOf8LackBalanceForState {
    pub fn new(account_id: String, amount: String) -> ActionErrorKindOneOf8LackBalanceForState {
        ActionErrorKindOneOf8LackBalanceForState {
            account_id,
            amount,
        }
    }
}

