/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf4 : Administrative actions like `DeployContract`, `Stake`, `AddKey`, `DeleteKey`. can be proceed only if sender=receiver or the first TX action is a `CreateAccount` action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf4 {
    #[serde(rename = "ActorNoPermission")]
    pub actor_no_permission: Box<models::ActionErrorKindOneOf4ActorNoPermission>,
}

impl ActionErrorKindOneOf4 {
    /// Administrative actions like `DeployContract`, `Stake`, `AddKey`, `DeleteKey`. can be proceed only if sender=receiver or the first TX action is a `CreateAccount` action
    pub fn new(actor_no_permission: models::ActionErrorKindOneOf4ActorNoPermission) -> ActionErrorKindOneOf4 {
        ActionErrorKindOneOf4 {
            actor_no_permission: Box::new(actor_no_permission),
        }
    }
}

