/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf9 : The transaction includes a feature that the current protocol version does not support.  Note: we stringify the protocol feature name instead of using `ProtocolFeature` here because we don't want to leak the internals of that type into observable borsh serialization.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf9 {
    #[serde(rename = "UnsupportedProtocolFeature")]
    pub unsupported_protocol_feature: Box<models::ActionsValidationErrorOneOf9UnsupportedProtocolFeature>,
}

impl ActionsValidationErrorOneOf9 {
    /// The transaction includes a feature that the current protocol version does not support.  Note: we stringify the protocol feature name instead of using `ProtocolFeature` here because we don't want to leak the internals of that type into observable borsh serialization.
    pub fn new(unsupported_protocol_feature: models::ActionsValidationErrorOneOf9UnsupportedProtocolFeature) -> ActionsValidationErrorOneOf9 {
        ActionsValidationErrorOneOf9 {
            unsupported_protocol_feature: Box::new(unsupported_protocol_feature),
        }
    }
}

