/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf {
    #[serde(rename = "DeployContract")]
    pub deploy_contract: Box<models::ActionViewOneOfDeployContract>,
}

impl ActionViewOneOf {
    pub fn new(deploy_contract: models::ActionViewOneOfDeployContract) -> ActionViewOneOf {
        ActionViewOneOf {
            deploy_contract: Box::new(deploy_contract),
        }
    }
}

