/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Action {
    ActionOneOf(Box<models::ActionOneOf>),
    ActionOneOf1(Box<models::ActionOneOf1>),
    ActionOneOf2(Box<models::ActionOneOf2>),
    ActionOneOf3(Box<models::ActionOneOf3>),
    ActionOneOf4(Box<models::ActionOneOf4>),
    ActionOneOf5(Box<models::ActionOneOf5>),
    ActionOneOf6(Box<models::ActionOneOf6>),
    ActionOneOf7(Box<models::ActionOneOf7>),
    ActionOneOf8(Box<models::ActionOneOf8>),
    ActionOneOf9(Box<models::ActionOneOf9>),
    ActionOneOf10(Box<models::ActionOneOf10>),
}

impl Default for Action {
    fn default() -> Self {
        Self::ActionOneOf(Default::default())
    }
}

