/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf4AddKey {
    #[serde(rename = "public_key")]
    pub public_key: String,
    #[serde(rename = "access_key")]
    pub access_key: Box<models::AccessKeyView>,
}

impl ActionViewOneOf4AddKey {
    pub fn new(public_key: String, access_key: models::AccessKeyView) -> ActionViewOneOf4AddKey {
        ActionViewOneOf4AddKey {
            public_key,
            access_key: Box::new(access_key),
        }
    }
}

