/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOfTotalPrepaidGasExceeded {
    #[serde(rename = "total_prepaid_gas")]
    pub total_prepaid_gas: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl ActionsValidationErrorOneOfTotalPrepaidGasExceeded {
    pub fn new(total_prepaid_gas: i32, limit: i32) -> ActionsValidationErrorOneOfTotalPrepaidGasExceeded {
        ActionsValidationErrorOneOfTotalPrepaidGasExceeded {
            total_prepaid_gas,
            limit,
        }
    }
}

