/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf11 {
    #[serde(rename = "InsufficientStake")]
    pub insufficient_stake: Box<models::ActionErrorKindOneOf11InsufficientStake>,
}

impl ActionErrorKindOneOf11 {
    pub fn new(insufficient_stake: models::ActionErrorKindOneOf11InsufficientStake) -> ActionErrorKindOneOf11 {
        ActionErrorKindOneOf11 {
            insufficient_stake: Box::new(insufficient_stake),
        }
    }
}

