/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf15 : Delete account whose state is large is temporarily banned.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf15 {
    #[serde(rename = "DeleteAccountWithLargeState")]
    pub delete_account_with_large_state: Box<models::ActionViewOneOf11UseGlobalContractByAccountId>,
}

impl ActionErrorKindOneOf15 {
    /// Delete account whose state is large is temporarily banned.
    pub fn new(delete_account_with_large_state: models::ActionViewOneOf11UseGlobalContractByAccountId) -> ActionErrorKindOneOf15 {
        ActionErrorKindOneOf15 {
            delete_account_with_large_state: Box::new(delete_account_with_large_state),
        }
    }
}

