/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf11 {
    #[serde(rename = "UseGlobalContractByAccountId")]
    pub use_global_contract_by_account_id: Box<models::ActionViewOneOf11UseGlobalContractByAccountId>,
}

impl ActionViewOneOf11 {
    pub fn new(use_global_contract_by_account_id: models::ActionViewOneOf11UseGlobalContractByAccountId) -> ActionViewOneOf11 {
        ActionViewOneOf11 {
            use_global_contract_by_account_id: Box::new(use_global_contract_by_account_id),
        }
    }
}

