/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf8 : An attempt to stake with a public key that is not convertible to ristretto.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf8 {
    #[serde(rename = "UnsuitableStakingKey")]
    pub unsuitable_staking_key: Box<models::ActionViewOneOf5DeleteKey>,
}

impl ActionsValidationErrorOneOf8 {
    /// An attempt to stake with a public key that is not convertible to ristretto.
    pub fn new(unsuitable_staking_key: models::ActionViewOneOf5DeleteKey) -> ActionsValidationErrorOneOf8 {
        ActionsValidationErrorOneOf8 {
            unsuitable_staking_key: Box::new(unsuitable_staking_key),
        }
    }
}

