/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded {
    #[serde(rename = "total_number_of_actions")]
    pub total_number_of_actions: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded {
    pub fn new(total_number_of_actions: i32, limit: i32) -> ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded {
        ActionsValidationErrorOneOf1TotalNumberOfActionsExceeded {
            total_number_of_actions,
            limit,
        }
    }
}

