/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf20GlobalContractDoesNotExist {
    #[serde(rename = "identifier")]
    pub identifier: Box<models::GlobalContractIdentifier>,
}

impl ActionErrorKindOneOf20GlobalContractDoesNotExist {
    pub fn new(identifier: models::GlobalContractIdentifier) -> ActionErrorKindOneOf20GlobalContractDoesNotExist {
        ActionErrorKindOneOf20GlobalContractDoesNotExist {
            identifier: Box::new(identifier),
        }
    }
}

