/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionOneOf3 {
    #[serde(rename = "Transfer")]
    pub transfer: Box<models::TransferAction>,
}

impl ActionOneOf3 {
    pub fn new(transfer: models::TransferAction) -> ActionOneOf3 {
        ActionOneOf3 {
            transfer: Box::new(transfer),
        }
    }
}

