/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionsValidationErrorOneOf5 : The size of the contract code exceeded the limit in a DeployContract action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf5 {
    #[serde(rename = "ContractSizeExceeded")]
    pub contract_size_exceeded: Box<models::HostErrorOneOf15ContractSizeExceeded>,
}

impl ActionsValidationErrorOneOf5 {
    /// The size of the contract code exceeded the limit in a DeployContract action.
    pub fn new(contract_size_exceeded: models::HostErrorOneOf15ContractSizeExceeded) -> ActionsValidationErrorOneOf5 {
        ActionsValidationErrorOneOf5 {
            contract_size_exceeded: Box::new(contract_size_exceeded),
        }
    }
}

