/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf18 : DelegateAction nonce must be greater sender[public_key].nonce
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf18 {
    #[serde(rename = "DelegateActionInvalidNonce")]
    pub delegate_action_invalid_nonce: Box<models::ActionErrorKindOneOf18DelegateActionInvalidNonce>,
}

impl ActionErrorKindOneOf18 {
    /// DelegateAction nonce must be greater sender[public_key].nonce
    pub fn new(delegate_action_invalid_nonce: models::ActionErrorKindOneOf18DelegateActionInvalidNonce) -> ActionErrorKindOneOf18 {
        ActionErrorKindOneOf18 {
            delegate_action_invalid_nonce: Box::new(delegate_action_invalid_nonce),
        }
    }
}

