/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf12 : An error occurred during a `FunctionCall` Action, parameter is debug message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf12 {
    #[serde(rename = "FunctionCallError")]
    pub function_call_error: Box<models::FunctionCallError>,
}

impl ActionErrorKindOneOf12 {
    /// An error occurred during a `FunctionCall` Action, parameter is debug message.
    pub fn new(function_call_error: models::FunctionCallError) -> ActionErrorKindOneOf12 {
        ActionErrorKindOneOf12 {
            function_call_error: Box::new(function_call_error),
        }
    }
}

