/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf8 {
    #[serde(rename = "DeployGlobalContract")]
    pub deploy_global_contract: Box<models::ActionViewOneOfDeployContract>,
}

impl ActionViewOneOf8 {
    pub fn new(deploy_global_contract: models::ActionViewOneOfDeployContract) -> ActionViewOneOf8 {
        ActionViewOneOf8 {
            deploy_global_contract: Box::new(deploy_global_contract),
        }
    }
}

