/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionViewOneOf9 {
    #[serde(rename = "DeployGlobalContractByAccountId")]
    pub deploy_global_contract_by_account_id: Box<models::ActionViewOneOfDeployContract>,
}

impl ActionViewOneOf9 {
    pub fn new(deploy_global_contract_by_account_id: models::ActionViewOneOfDeployContract) -> ActionViewOneOf9 {
        ActionViewOneOf9 {
            deploy_global_contract_by_account_id: Box::new(deploy_global_contract_by_account_id),
        }
    }
}

