/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf10 : The account doesn't have enough balance to increase the stake.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf10 {
    #[serde(rename = "TriesToStake")]
    pub tries_to_stake: Box<models::ActionErrorKindOneOf10TriesToStake>,
}

impl ActionErrorKindOneOf10 {
    /// The account doesn't have enough balance to increase the stake.
    pub fn new(tries_to_stake: models::ActionErrorKindOneOf10TriesToStake) -> ActionErrorKindOneOf10 {
        ActionErrorKindOneOf10 {
            tries_to_stake: Box::new(tries_to_stake),
        }
    }
}

