/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionErrorKindOneOf14 : Error occurs when a `CreateAccount` action is called on a NEAR-implicit or ETH-implicit account. See NEAR-implicit account creation NEP: <https://github.com/nearprotocol/NEPs/pull/71>. Also, see ETH-implicit account creation NEP: <https://github.com/near/NEPs/issues/518>.  TODO(#8598): This error is named very poorly. A better name would be `OnlyNamedAccountCreationAllowed`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionErrorKindOneOf14 {
    #[serde(rename = "OnlyImplicitAccountCreationAllowed")]
    pub only_implicit_account_creation_allowed: Box<models::ActionViewOneOf11UseGlobalContractByAccountId>,
}

impl ActionErrorKindOneOf14 {
    /// Error occurs when a `CreateAccount` action is called on a NEAR-implicit or ETH-implicit account. See NEAR-implicit account creation NEP: <https://github.com/nearprotocol/NEPs/pull/71>. Also, see ETH-implicit account creation NEP: <https://github.com/near/NEPs/issues/518>.  TODO(#8598): This error is named very poorly. A better name would be `OnlyNamedAccountCreationAllowed`.
    pub fn new(only_implicit_account_creation_allowed: models::ActionViewOneOf11UseGlobalContractByAccountId) -> ActionErrorKindOneOf14 {
        ActionErrorKindOneOf14 {
            only_implicit_account_creation_allowed: Box::new(only_implicit_account_creation_allowed),
        }
    }
}

