/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionView {
    String(String),
    ActionViewOneOf(Box<models::ActionViewOneOf>),
    ActionViewOneOf1(Box<models::ActionViewOneOf1>),
    ActionViewOneOf2(Box<models::ActionViewOneOf2>),
    ActionViewOneOf3(Box<models::ActionViewOneOf3>),
    ActionViewOneOf4(Box<models::ActionViewOneOf4>),
    ActionViewOneOf5(Box<models::ActionViewOneOf5>),
    ActionViewOneOf6(Box<models::ActionViewOneOf6>),
    ActionViewOneOf7(Box<models::ActionViewOneOf7>),
    ActionViewOneOf8(Box<models::ActionViewOneOf8>),
    ActionViewOneOf9(Box<models::ActionViewOneOf9>),
    ActionViewOneOf10(Box<models::ActionViewOneOf10>),
    ActionViewOneOf11(Box<models::ActionViewOneOf11>),
}

impl Default for ActionView {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

