/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded {
    #[serde(rename = "total_number_of_bytes")]
    pub total_number_of_bytes: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded {
    pub fn new(total_number_of_bytes: i32, limit: i32) -> ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded {
        ActionsValidationErrorOneOf2AddKeyMethodNamesNumberOfBytesExceeded {
            total_number_of_bytes,
            limit,
        }
    }
}

