/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddKeyAction {
    /// A public key which will be associated with an access_key
    #[serde(rename = "public_key")]
    pub public_key: String,
    /// An access key with the permission
    #[serde(rename = "access_key")]
    pub access_key: Box<models::AccessKey>,
}

impl AddKeyAction {
    pub fn new(public_key: String, access_key: models::AccessKey) -> AddKeyAction {
        AddKeyAction {
            public_key,
            access_key: Box::new(access_key),
        }
    }
}

