/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompilationErrorOneOf {
    #[serde(rename = "CodeDoesNotExist")]
    pub code_does_not_exist: Box<models::ActionViewOneOf11UseGlobalContractByAccountId>,
}

impl CompilationErrorOneOf {
    pub fn new(code_does_not_exist: models::ActionViewOneOf11UseGlobalContractByAccountId) -> CompilationErrorOneOf {
        CompilationErrorOneOf {
            code_does_not_exist: Box::new(code_does_not_exist),
        }
    }
}

