/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompilationErrorOneOf1 {
    #[serde(rename = "PrepareError")]
    pub prepare_error: Box<models::PrepareError>,
}

impl CompilationErrorOneOf1 {
    pub fn new(prepare_error: models::PrepareError) -> CompilationErrorOneOf1 {
        CompilationErrorOneOf1 {
            prepare_error: Box::new(prepare_error),
        }
    }
}

