/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CompilationError {
    CompilationErrorOneOf(Box<models::CompilationErrorOneOf>),
    CompilationErrorOneOf1(Box<models::CompilationErrorOneOf1>),
    CompilationErrorOneOf2(Box<models::CompilationErrorOneOf2>),
}

impl Default for CompilationError {
    fn default() -> Self {
        Self::CompilationErrorOneOf(Default::default())
    }
}

