/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CostGasUsed {
    #[serde(rename = "cost_category")]
    pub cost_category: String,
    #[serde(rename = "cost")]
    pub cost: String,
    #[serde(rename = "gas_used")]
    pub gas_used: String,
}

impl CostGasUsed {
    pub fn new(cost_category: String, cost: String, gas_used: String) -> CostGasUsed {
        CostGasUsed {
            cost_category,
            cost,
            gas_used,
        }
    }
}

