/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeployGlobalContractAction : Deploy global contract action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployGlobalContractAction {
    /// WebAssembly binary
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "deploy_mode")]
    pub deploy_mode: Box<models::GlobalContractDeployMode>,
}

impl DeployGlobalContractAction {
    /// Deploy global contract action
    pub fn new(code: String, deploy_mode: models::GlobalContractDeployMode) -> DeployGlobalContractAction {
        DeployGlobalContractAction {
            code,
            deploy_mode: Box::new(deploy_mode),
        }
    }
}

