/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeployContractAction : Deploy contract action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployContractAction {
    /// WebAssembly binary
    #[serde(rename = "code")]
    pub code: String,
}

impl DeployContractAction {
    /// Deploy contract action
    pub fn new(code: String) -> DeployContractAction {
        DeployContractAction {
            code,
        }
    }
}

