/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionOutcomeWithIdView {
    #[serde(rename = "proof")]
    pub proof: Vec<models::MerklePathItem>,
    #[serde(rename = "block_hash")]
    pub block_hash: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "outcome")]
    pub outcome: Box<models::ExecutionOutcomeView>,
}

impl ExecutionOutcomeWithIdView {
    pub fn new(proof: Vec<models::MerklePathItem>, block_hash: String, id: String, outcome: models::ExecutionOutcomeView) -> ExecutionOutcomeWithIdView {
        ExecutionOutcomeWithIdView {
            proof,
            block_hash,
            id,
            outcome: Box::new(outcome),
        }
    }
}

