/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExecutionStatusView {
    /// The execution is pending or unknown.
    String(String),
    ExecutionStatusViewOneOf(Box<models::ExecutionStatusViewOneOf>),
    ExecutionStatusViewOneOf1(Box<models::ExecutionStatusViewOneOf1>),
    ExecutionStatusViewOneOf2(Box<models::ExecutionStatusViewOneOf2>),
}

impl Default for ExecutionStatusView {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

