/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExecutionStatusViewOneOf1 : The final action succeeded and returned some value or an empty vec encoded in base64.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionStatusViewOneOf1 {
    #[serde(rename = "SuccessValue")]
    pub success_value: String,
}

impl ExecutionStatusViewOneOf1 {
    /// The final action succeeded and returned some value or an empty vec encoded in base64.
    pub fn new(success_value: String) -> ExecutionStatusViewOneOf1 {
        ExecutionStatusViewOneOf1 {
            success_value,
        }
    }
}

