/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExecutionStatusViewOneOf : The execution has failed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionStatusViewOneOf {
    #[serde(rename = "Failure")]
    pub failure: Box<models::TxExecutionError>,
}

impl ExecutionStatusViewOneOf {
    /// The execution has failed.
    pub fn new(failure: models::TxExecutionError) -> ExecutionStatusViewOneOf {
        ExecutionStatusViewOneOf {
            failure: Box::new(failure),
        }
    }
}

