/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionMetadataView {
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "gas_profile", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gas_profile: Option<Option<Vec<models::CostGasUsed>>>,
}

impl ExecutionMetadataView {
    pub fn new(version: i32) -> ExecutionMetadataView {
        ExecutionMetadataView {
            version,
            gas_profile: None,
        }
    }
}

