/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExecutionStatusViewOneOf2 : The final action of the receipt returned a promise or the signed transaction was converted to a receipt. Contains the receipt_id of the generated receipt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionStatusViewOneOf2 {
    #[serde(rename = "SuccessReceiptId")]
    pub success_receipt_id: String,
}

impl ExecutionStatusViewOneOf2 {
    /// The final action of the receipt returned a promise or the signed transaction was converted to a receipt. Contains the receipt_id of the generated receipt.
    pub fn new(success_receipt_id: String) -> ExecutionStatusViewOneOf2 {
        ExecutionStatusViewOneOf2 {
            success_receipt_id,
        }
    }
}

