/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FinalExecutionStatus {
    /// The execution has not yet started.
    String(String),
    /// The execution has started and still going.
    String(String),
    FinalExecutionStatusOneOf(Box<models::FinalExecutionStatusOneOf>),
    FinalExecutionStatusOneOf1(Box<models::FinalExecutionStatusOneOf1>),
}

impl Default for FinalExecutionStatus {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

