/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FinalExecutionStatusOneOf : The execution has failed with the given error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinalExecutionStatusOneOf {
    #[serde(rename = "Failure")]
    pub failure: Box<models::TxExecutionError>,
}

impl FinalExecutionStatusOneOf {
    /// The execution has failed with the given error.
    pub fn new(failure: models::TxExecutionError) -> FinalExecutionStatusOneOf {
        FinalExecutionStatusOneOf {
            failure: Box::new(failure),
        }
    }
}

