/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf1LinkError {
    #[serde(rename = "msg")]
    pub msg: String,
}

impl FunctionCallErrorOneOf1LinkError {
    pub fn new(msg: String) -> FunctionCallErrorOneOf1LinkError {
        FunctionCallErrorOneOf1LinkError {
            msg,
        }
    }
}

