/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallErrorOneOf1 : Wasm binary env link error  Note: this is only to deserialize old data, use execution error for new data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf1 {
    #[serde(rename = "LinkError")]
    pub link_error: Box<models::FunctionCallErrorOneOf1LinkError>,
}

impl FunctionCallErrorOneOf1 {
    /// Wasm binary env link error  Note: this is only to deserialize old data, use execution error for new data
    pub fn new(link_error: models::FunctionCallErrorOneOf1LinkError) -> FunctionCallErrorOneOf1 {
        FunctionCallErrorOneOf1 {
            link_error: Box::new(link_error),
        }
    }
}

