/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallErrorOneOf2 : Import/export resolve error
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf2 {
    #[serde(rename = "MethodResolveError")]
    pub method_resolve_error: models::MethodResolveError,
}

impl FunctionCallErrorOneOf2 {
    /// Import/export resolve error
    pub fn new(method_resolve_error: models::MethodResolveError) -> FunctionCallErrorOneOf2 {
        FunctionCallErrorOneOf2 {
            method_resolve_error,
        }
    }
}

