/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallErrorOneOf : Wasm compilation error
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf {
    #[serde(rename = "CompilationError")]
    pub compilation_error: Box<models::CompilationError>,
}

impl FunctionCallErrorOneOf {
    /// Wasm compilation error
    pub fn new(compilation_error: models::CompilationError) -> FunctionCallErrorOneOf {
        FunctionCallErrorOneOf {
            compilation_error: Box::new(compilation_error),
        }
    }
}

