/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallErrorOneOf3 : A trap happened during execution of a binary  Note: this is only to deserialize old data, use execution error for new data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf3 {
    #[serde(rename = "WasmTrap")]
    pub wasm_trap: Box<models::WasmTrap>,
}

impl FunctionCallErrorOneOf3 {
    /// A trap happened during execution of a binary  Note: this is only to deserialize old data, use execution error for new data
    pub fn new(wasm_trap: models::WasmTrap) -> FunctionCallErrorOneOf3 {
        FunctionCallErrorOneOf3 {
            wasm_trap: Box::new(wasm_trap),
        }
    }
}

