/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallPermission : Grants limited permission to make transactions with FunctionCallActions The permission can limit the allowed balance to be spent on the prepaid gas. It also restrict the account ID of the receiver for this function call. It also can restrict the method name for the allowed function calls.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallPermission {
    /// Allowance is a balance limit to use by this access key to pay for function call gas and transaction fees. When this access key is used, both account balance and the allowance is decreased by the same value. `None` means unlimited allowance. NOTE: To change or increase the allowance, the old access key needs to be deleted and a new access key should be created.
    #[serde(rename = "allowance")]
    pub allowance: String,
    /// The access key only allows transactions with the given receiver's account id.
    #[serde(rename = "receiver_id")]
    pub receiver_id: String,
    /// A list of method names that can be used. The access key only allows transactions with the function call of one of the given method names. Empty list means any method name can be used.
    #[serde(rename = "method_names")]
    pub method_names: Vec<String>,
}

impl FunctionCallPermission {
    /// Grants limited permission to make transactions with FunctionCallActions The permission can limit the allowed balance to be spent on the prepaid gas. It also restrict the account ID of the receiver for this function call. It also can restrict the method name for the allowed function calls.
    pub fn new(allowance: String, receiver_id: String, method_names: Vec<String>) -> FunctionCallPermission {
        FunctionCallPermission {
            allowance,
            receiver_id,
            method_names,
        }
    }
}

