/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallErrorOneOf4 : Note: this is only to deserialize old data, use execution error for new data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf4 {
    #[serde(rename = "HostError")]
    pub host_error: Box<models::HostError>,
}

impl FunctionCallErrorOneOf4 {
    /// Note: this is only to deserialize old data, use execution error for new data
    pub fn new(host_error: models::HostError) -> FunctionCallErrorOneOf4 {
        FunctionCallErrorOneOf4 {
            host_error: Box::new(host_error),
        }
    }
}

