/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionCallErrorOneOf5 {
    #[serde(rename = "ExecutionError")]
    pub execution_error: String,
}

impl FunctionCallErrorOneOf5 {
    pub fn new(execution_error: String) -> FunctionCallErrorOneOf5 {
        FunctionCallErrorOneOf5 {
            execution_error,
        }
    }
}

