/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionCallError : Serializable version of `near-vm-runner::FunctionCallError`.  Must never reorder/remove elements, can only add new variants at the end (but do that very carefully). It describes stable serialization format, and only used by serialization logic.
/// Serializable version of `near-vm-runner::FunctionCallError`.  Must never reorder/remove elements, can only add new variants at the end (but do that very carefully). It describes stable serialization format, and only used by serialization logic.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FunctionCallError {
    String(String),
    FunctionCallErrorOneOf(Box<models::FunctionCallErrorOneOf>),
    FunctionCallErrorOneOf1(Box<models::FunctionCallErrorOneOf1>),
    FunctionCallErrorOneOf2(Box<models::FunctionCallErrorOneOf2>),
    FunctionCallErrorOneOf3(Box<models::FunctionCallErrorOneOf3>),
    FunctionCallErrorOneOf4(Box<models::FunctionCallErrorOneOf4>),
    FunctionCallErrorOneOf5(Box<models::FunctionCallErrorOneOf5>),
}

impl Default for FunctionCallError {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

