/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GlobalContractIdentifierOneOf {
    #[serde(rename = "CodeHash")]
    pub code_hash: String,
}

impl GlobalContractIdentifierOneOf {
    pub fn new(code_hash: String) -> GlobalContractIdentifierOneOf {
        GlobalContractIdentifierOneOf {
            code_hash,
        }
    }
}

