/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GlobalContractIdentifier {
    GlobalContractIdentifierOneOf(Box<models::GlobalContractIdentifierOneOf>),
    GlobalContractIdentifierOneOf1(Box<models::GlobalContractIdentifierOneOf1>),
}

impl Default for GlobalContractIdentifier {
    fn default() -> Self {
        Self::GlobalContractIdentifierOneOf(Default::default())
    }
}

