/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GlobalContractDeployMode {
    /// Contract is deployed under its code hash. Users will be able reference it by that hash. This effectively makes the contract immutable.
    String(String),
    /// Contract is deployed under the owner account id. Users will be able reference it by that account id. This allows the owner to update the contract for all its users.
    String(String),
}

impl Default for GlobalContractDeployMode {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

