/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf11 : The total log length exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf11 {
    #[serde(rename = "TotalLogLengthExceeded")]
    pub total_log_length_exceeded: Box<models::HostErrorOneOf9KeyLengthExceeded>,
}

impl HostErrorOneOf11 {
    /// The total log length exceeded the limit.
    pub fn new(total_log_length_exceeded: models::HostErrorOneOf9KeyLengthExceeded) -> HostErrorOneOf11 {
        HostErrorOneOf11 {
            total_log_length_exceeded: Box::new(total_log_length_exceeded),
        }
    }
}

