/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf : Smart contract panicked
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf {
    #[serde(rename = "GuestPanic")]
    pub guest_panic: Box<models::HostErrorOneOfGuestPanic>,
}

impl HostErrorOneOf {
    /// Smart contract panicked
    pub fn new(guest_panic: models::HostErrorOneOfGuestPanic) -> HostErrorOneOf {
        HostErrorOneOf {
            guest_panic: Box::new(guest_panic),
        }
    }
}

