/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf10 : The storage value length exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf10 {
    #[serde(rename = "ValueLengthExceeded")]
    pub value_length_exceeded: Box<models::HostErrorOneOf9KeyLengthExceeded>,
}

impl HostErrorOneOf10 {
    /// The storage value length exceeded the limit.
    pub fn new(value_length_exceeded: models::HostErrorOneOf9KeyLengthExceeded) -> HostErrorOneOf10 {
        HostErrorOneOf10 {
            value_length_exceeded: Box::new(value_length_exceeded),
        }
    }
}

