/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf7 : `method_name` is not allowed in view calls
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf7 {
    #[serde(rename = "ProhibitedInView")]
    pub prohibited_in_view: Box<models::HostErrorOneOf7ProhibitedInView>,
}

impl HostErrorOneOf7 {
    /// `method_name` is not allowed in view calls
    pub fn new(prohibited_in_view: models::HostErrorOneOf7ProhibitedInView) -> HostErrorOneOf7 {
        HostErrorOneOf7 {
            prohibited_in_view: Box::new(prohibited_in_view),
        }
    }
}

