/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf13 : The maximum number of input data dependencies exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf13 {
    #[serde(rename = "NumberInputDataDependenciesExceeded")]
    pub number_input_data_dependencies_exceeded: Box<models::HostErrorOneOf13NumberInputDataDependenciesExceeded>,
}

impl HostErrorOneOf13 {
    /// The maximum number of input data dependencies exceeded the limit.
    pub fn new(number_input_data_dependencies_exceeded: models::HostErrorOneOf13NumberInputDataDependenciesExceeded) -> HostErrorOneOf13 {
        HostErrorOneOf13 {
            number_input_data_dependencies_exceeded: Box::new(number_input_data_dependencies_exceeded),
        }
    }
}

