/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf1 : `promise_idx` does not correspond to existing promises
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf1 {
    #[serde(rename = "InvalidPromiseIndex")]
    pub invalid_promise_index: Box<models::HostErrorOneOf1InvalidPromiseIndex>,
}

impl HostErrorOneOf1 {
    /// `promise_idx` does not correspond to existing promises
    pub fn new(invalid_promise_index: models::HostErrorOneOf1InvalidPromiseIndex) -> HostErrorOneOf1 {
        HostErrorOneOf1 {
            invalid_promise_index: Box::new(invalid_promise_index),
        }
    }
}

