/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf4 : Iterator `iterator_index` was invalidated after its creation by performing a mutable operation on trie
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf4 {
    #[serde(rename = "IteratorWasInvalidated")]
    pub iterator_was_invalidated: Box<models::HostErrorOneOf4IteratorWasInvalidated>,
}

impl HostErrorOneOf4 {
    /// Iterator `iterator_index` was invalidated after its creation by performing a mutable operation on trie
    pub fn new(iterator_was_invalidated: models::HostErrorOneOf4IteratorWasInvalidated) -> HostErrorOneOf4 {
        HostErrorOneOf4 {
            iterator_was_invalidated: Box::new(iterator_was_invalidated),
        }
    }
}

