/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf7ProhibitedInView {
    #[serde(rename = "method_name")]
    pub method_name: String,
}

impl HostErrorOneOf7ProhibitedInView {
    pub fn new(method_name: String) -> HostErrorOneOf7ProhibitedInView {
        HostErrorOneOf7ProhibitedInView {
            method_name,
        }
    }
}

