/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf3InvalidRegisterId {
    #[serde(rename = "register_id")]
    pub register_id: i32,
}

impl HostErrorOneOf3InvalidRegisterId {
    pub fn new(register_id: i32) -> HostErrorOneOf3InvalidRegisterId {
        HostErrorOneOf3InvalidRegisterId {
            register_id,
        }
    }
}

