/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf5InvalidReceiptIndex {
    #[serde(rename = "receipt_index")]
    pub receipt_index: i32,
}

impl HostErrorOneOf5InvalidReceiptIndex {
    pub fn new(receipt_index: i32) -> HostErrorOneOf5InvalidReceiptIndex {
        HostErrorOneOf5InvalidReceiptIndex {
            receipt_index,
        }
    }
}

