/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf15ContractSizeExceeded {
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl HostErrorOneOf15ContractSizeExceeded {
    pub fn new(size: i32, limit: i32) -> HostErrorOneOf15ContractSizeExceeded {
        HostErrorOneOf15ContractSizeExceeded {
            size,
            limit,
        }
    }
}

