/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf3 : Accessed invalid register id
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf3 {
    #[serde(rename = "InvalidRegisterId")]
    pub invalid_register_id: Box<models::HostErrorOneOf3InvalidRegisterId>,
}

impl HostErrorOneOf3 {
    /// Accessed invalid register id
    pub fn new(invalid_register_id: models::HostErrorOneOf3InvalidRegisterId) -> HostErrorOneOf3 {
        HostErrorOneOf3 {
            invalid_register_id: Box::new(invalid_register_id),
        }
    }
}

