/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf9KeyLengthExceeded {
    #[serde(rename = "length")]
    pub length: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl HostErrorOneOf9KeyLengthExceeded {
    pub fn new(length: i32, limit: i32) -> HostErrorOneOf9KeyLengthExceeded {
        HostErrorOneOf9KeyLengthExceeded {
            length,
            limit,
        }
    }
}

