/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf18 : Invalid input to alt_bn128 family of functions (e.g., point which isn't on the curve).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf18 {
    #[serde(rename = "AltBn128InvalidInput")]
    pub alt_bn128_invalid_input: Box<models::FunctionCallErrorOneOf1LinkError>,
}

impl HostErrorOneOf18 {
    /// Invalid input to alt_bn128 family of functions (e.g., point which isn't on the curve).
    pub fn new(alt_bn128_invalid_input: models::FunctionCallErrorOneOf1LinkError) -> HostErrorOneOf18 {
        HostErrorOneOf18 {
            alt_bn128_invalid_input: Box::new(alt_bn128_invalid_input),
        }
    }
}

