/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf15 : The contract size for DeployContract action exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf15 {
    #[serde(rename = "ContractSizeExceeded")]
    pub contract_size_exceeded: Box<models::HostErrorOneOf15ContractSizeExceeded>,
}

impl HostErrorOneOf15 {
    /// The contract size for DeployContract action exceeded the limit.
    pub fn new(contract_size_exceeded: models::HostErrorOneOf15ContractSizeExceeded) -> HostErrorOneOf15 {
        HostErrorOneOf15 {
            contract_size_exceeded: Box::new(contract_size_exceeded),
        }
    }
}

