/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf14 : The returned value length exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf14 {
    #[serde(rename = "ReturnedValueLengthExceeded")]
    pub returned_value_length_exceeded: Box<models::HostErrorOneOf9KeyLengthExceeded>,
}

impl HostErrorOneOf14 {
    /// The returned value length exceeded the limit.
    pub fn new(returned_value_length_exceeded: models::HostErrorOneOf9KeyLengthExceeded) -> HostErrorOneOf14 {
        HostErrorOneOf14 {
            returned_value_length_exceeded: Box::new(returned_value_length_exceeded),
        }
    }
}

