/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf2 : Accessed invalid promise result index
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf2 {
    #[serde(rename = "InvalidPromiseResultIndex")]
    pub invalid_promise_result_index: Box<models::HostErrorOneOf2InvalidPromiseResultIndex>,
}

impl HostErrorOneOf2 {
    /// Accessed invalid promise result index
    pub fn new(invalid_promise_result_index: models::HostErrorOneOf2InvalidPromiseResultIndex) -> HostErrorOneOf2 {
        HostErrorOneOf2 {
            invalid_promise_result_index: Box::new(invalid_promise_result_index),
        }
    }
}

