/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf12NumberPromisesExceeded {
    #[serde(rename = "number_of_promises")]
    pub number_of_promises: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl HostErrorOneOf12NumberPromisesExceeded {
    pub fn new(number_of_promises: i32, limit: i32) -> HostErrorOneOf12NumberPromisesExceeded {
        HostErrorOneOf12NumberPromisesExceeded {
            number_of_promises,
            limit,
        }
    }
}

