/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf16 : The host function was deprecated.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf16 {
    #[serde(rename = "Deprecated")]
    pub deprecated: Box<models::HostErrorOneOf7ProhibitedInView>,
}

impl HostErrorOneOf16 {
    /// The host function was deprecated.
    pub fn new(deprecated: models::HostErrorOneOf7ProhibitedInView) -> HostErrorOneOf16 {
        HostErrorOneOf16 {
            deprecated: Box::new(deprecated),
        }
    }
}

