/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf17 : General errors for ECDSA recover.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf17 {
    #[serde(rename = "ECRecoverError")]
    pub ec_recover_error: Box<models::FunctionCallErrorOneOf1LinkError>,
}

impl HostErrorOneOf17 {
    /// General errors for ECDSA recover.
    pub fn new(ec_recover_error: models::FunctionCallErrorOneOf1LinkError) -> HostErrorOneOf17 {
        HostErrorOneOf17 {
            ec_recover_error: Box::new(ec_recover_error),
        }
    }
}

