/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf1InvalidPromiseIndex {
    #[serde(rename = "promise_idx")]
    pub promise_idx: i32,
}

impl HostErrorOneOf1InvalidPromiseIndex {
    pub fn new(promise_idx: i32) -> HostErrorOneOf1InvalidPromiseIndex {
        HostErrorOneOf1InvalidPromiseIndex {
            promise_idx,
        }
    }
}

