/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf12 : The maximum number of promises within a FunctionCall exceeded the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf12 {
    #[serde(rename = "NumberPromisesExceeded")]
    pub number_promises_exceeded: Box<models::HostErrorOneOf12NumberPromisesExceeded>,
}

impl HostErrorOneOf12 {
    /// The maximum number of promises within a FunctionCall exceeded the limit.
    pub fn new(number_promises_exceeded: models::HostErrorOneOf12NumberPromisesExceeded) -> HostErrorOneOf12 {
        HostErrorOneOf12 {
            number_promises_exceeded: Box::new(number_promises_exceeded),
        }
    }
}

