/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf13NumberInputDataDependenciesExceeded {
    #[serde(rename = "number_of_input_data_dependencies")]
    pub number_of_input_data_dependencies: i32,
    #[serde(rename = "limit")]
    pub limit: i32,
}

impl HostErrorOneOf13NumberInputDataDependenciesExceeded {
    pub fn new(number_of_input_data_dependencies: i32, limit: i32) -> HostErrorOneOf13NumberInputDataDependenciesExceeded {
        HostErrorOneOf13NumberInputDataDependenciesExceeded {
            number_of_input_data_dependencies,
            limit,
        }
    }
}

