/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HostErrorOneOf5 : VM Logic returned an invalid receipt index
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HostErrorOneOf5 {
    #[serde(rename = "InvalidReceiptIndex")]
    pub invalid_receipt_index: Box<models::HostErrorOneOf5InvalidReceiptIndex>,
}

impl HostErrorOneOf5 {
    /// VM Logic returned an invalid receipt index
    pub fn new(invalid_receipt_index: models::HostErrorOneOf5InvalidReceiptIndex) -> HostErrorOneOf5 {
        HostErrorOneOf5 {
            invalid_receipt_index: Box::new(invalid_receipt_index),
        }
    }
}

