/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf7 : Signer account doesn't have enough balance after transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf7 {
    #[serde(rename = "LackBalanceForState")]
    pub lack_balance_for_state: Box<models::InvalidTxErrorOneOf7LackBalanceForState>,
}

impl InvalidTxErrorOneOf7 {
    /// Signer account doesn't have enough balance after transaction.
    pub fn new(lack_balance_for_state: models::InvalidTxErrorOneOf7LackBalanceForState) -> InvalidTxErrorOneOf7 {
        InvalidTxErrorOneOf7 {
            lack_balance_for_state: Box::new(lack_balance_for_state),
        }
    }
}

