/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf11 : The receiver shard of the transaction is too congested to accept new transactions at the moment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf11 {
    #[serde(rename = "ShardCongested")]
    pub shard_congested: Box<models::InvalidTxErrorOneOf11ShardCongested>,
}

impl InvalidTxErrorOneOf11 {
    /// The receiver shard of the transaction is too congested to accept new transactions at the moment.
    pub fn new(shard_congested: models::InvalidTxErrorOneOf11ShardCongested) -> InvalidTxErrorOneOf11 {
        InvalidTxErrorOneOf11 {
            shard_congested: Box::new(shard_congested),
        }
    }
}

