/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidAccessKeyErrorOneOf1 : Transaction `receiver_id` doesn't match the access key receiver_id
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidAccessKeyErrorOneOf1 {
    #[serde(rename = "ReceiverMismatch")]
    pub receiver_mismatch: Box<models::InvalidAccessKeyErrorOneOf1ReceiverMismatch>,
}

impl InvalidAccessKeyErrorOneOf1 {
    /// Transaction `receiver_id` doesn't match the access key receiver_id
    pub fn new(receiver_mismatch: models::InvalidAccessKeyErrorOneOf1ReceiverMismatch) -> InvalidAccessKeyErrorOneOf1 {
        InvalidAccessKeyErrorOneOf1 {
            receiver_mismatch: Box::new(receiver_mismatch),
        }
    }
}

