/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InvalidAccessKeyError {
    InvalidAccessKeyErrorOneOf(Box<models::InvalidAccessKeyErrorOneOf>),
    InvalidAccessKeyErrorOneOf1(Box<models::InvalidAccessKeyErrorOneOf1>),
    InvalidAccessKeyErrorOneOf2(Box<models::InvalidAccessKeyErrorOneOf2>),
    /// Transaction requires a full permission access key.
    String(String),
    InvalidAccessKeyErrorOneOf3(Box<models::InvalidAccessKeyErrorOneOf3>),
    /// Having a deposit with a function call action is not allowed with a function call access key.
    String(String),
}

impl Default for InvalidAccessKeyError {
    fn default() -> Self {
        Self::InvalidAccessKeyErrorOneOf(Default::default())
    }
}

