/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf10 {
    #[serde(rename = "StorageError")]
    pub storage_error: Box<models::StorageError>,
}

impl InvalidTxErrorOneOf10 {
    pub fn new(storage_error: models::StorageError) -> InvalidTxErrorOneOf10 {
        InvalidTxErrorOneOf10 {
            storage_error: Box::new(storage_error),
        }
    }
}

