/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf5 : TX receiver_id is not a valid AccountId
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf5 {
    #[serde(rename = "InvalidReceiverId")]
    pub invalid_receiver_id: Box<models::InvalidTxErrorOneOf5InvalidReceiverId>,
}

impl InvalidTxErrorOneOf5 {
    /// TX receiver_id is not a valid AccountId
    pub fn new(invalid_receiver_id: models::InvalidTxErrorOneOf5InvalidReceiverId) -> InvalidTxErrorOneOf5 {
        InvalidTxErrorOneOf5 {
            invalid_receiver_id: Box::new(invalid_receiver_id),
        }
    }
}

