/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf11ShardCongested {
    /// The congested shard.
    #[serde(rename = "shard_id")]
    pub shard_id: i32,
    /// A value between 0 (no congestion) and 1 (max congestion).
    #[serde(rename = "congestion_level")]
    pub congestion_level: f64,
}

impl InvalidTxErrorOneOf11ShardCongested {
    pub fn new(shard_id: i32, congestion_level: f64) -> InvalidTxErrorOneOf11ShardCongested {
        InvalidTxErrorOneOf11ShardCongested {
            shard_id,
            congestion_level,
        }
    }
}

