/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf6 : Account does not have enough balance to cover TX cost
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf6 {
    #[serde(rename = "NotEnoughBalance")]
    pub not_enough_balance: Box<models::InvalidTxErrorOneOf6NotEnoughBalance>,
}

impl InvalidTxErrorOneOf6 {
    /// Account does not have enough balance to cover TX cost
    pub fn new(not_enough_balance: models::InvalidTxErrorOneOf6NotEnoughBalance) -> InvalidTxErrorOneOf6 {
        InvalidTxErrorOneOf6 {
            not_enough_balance: Box::new(not_enough_balance),
        }
    }
}

