/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf1InvalidSignerId {
    #[serde(rename = "signer_id")]
    pub signer_id: String,
}

impl InvalidTxErrorOneOf1InvalidSignerId {
    pub fn new(signer_id: String) -> InvalidTxErrorOneOf1InvalidSignerId {
        InvalidTxErrorOneOf1InvalidSignerId {
            signer_id,
        }
    }
}

