/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf7LackBalanceForState {
    /// An account which doesn't have enough balance to cover storage.
    #[serde(rename = "signer_id")]
    pub signer_id: String,
    /// Required balance to cover the state.
    #[serde(rename = "amount")]
    pub amount: String,
}

impl InvalidTxErrorOneOf7LackBalanceForState {
    pub fn new(signer_id: String, amount: String) -> InvalidTxErrorOneOf7LackBalanceForState {
        InvalidTxErrorOneOf7LackBalanceForState {
            signer_id,
            amount,
        }
    }
}

