/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidAccessKeyErrorOneOf2 : Transaction method name isn't allowed by the access key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidAccessKeyErrorOneOf2 {
    #[serde(rename = "MethodNameMismatch")]
    pub method_name_mismatch: Box<models::HostErrorOneOf7ProhibitedInView>,
}

impl InvalidAccessKeyErrorOneOf2 {
    /// Transaction method name isn't allowed by the access key
    pub fn new(method_name_mismatch: models::HostErrorOneOf7ProhibitedInView) -> InvalidAccessKeyErrorOneOf2 {
        InvalidAccessKeyErrorOneOf2 {
            method_name_mismatch: Box::new(method_name_mismatch),
        }
    }
}

