/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf1 : TX signer_id is not a valid [`AccountId`]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf1 {
    #[serde(rename = "InvalidSignerId")]
    pub invalid_signer_id: Box<models::InvalidTxErrorOneOf1InvalidSignerId>,
}

impl InvalidTxErrorOneOf1 {
    /// TX signer_id is not a valid [`AccountId`]
    pub fn new(invalid_signer_id: models::InvalidTxErrorOneOf1InvalidSignerId) -> InvalidTxErrorOneOf1 {
        InvalidTxErrorOneOf1 {
            invalid_signer_id: Box::new(invalid_signer_id),
        }
    }
}

