/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf3InvalidNonce {
    #[serde(rename = "tx_nonce")]
    pub tx_nonce: i32,
    #[serde(rename = "ak_nonce")]
    pub ak_nonce: i32,
}

impl InvalidTxErrorOneOf3InvalidNonce {
    pub fn new(tx_nonce: i32, ak_nonce: i32) -> InvalidTxErrorOneOf3InvalidNonce {
        InvalidTxErrorOneOf3InvalidNonce {
            tx_nonce,
            ak_nonce,
        }
    }
}

