/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidAccessKeyErrorOneOf : The access key identified by the `public_key` doesn't exist for the account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidAccessKeyErrorOneOf {
    #[serde(rename = "AccessKeyNotFound")]
    pub access_key_not_found: Box<models::ActionErrorKindOneOf5DeleteKeyDoesNotExist>,
}

impl InvalidAccessKeyErrorOneOf {
    /// The access key identified by the `public_key` doesn't exist for the account
    pub fn new(access_key_not_found: models::ActionErrorKindOneOf5DeleteKeyDoesNotExist) -> InvalidAccessKeyErrorOneOf {
        InvalidAccessKeyErrorOneOf {
            access_key_not_found: Box::new(access_key_not_found),
        }
    }
}

