/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf2 : TX signer_id is not found in a storage
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf2 {
    #[serde(rename = "SignerDoesNotExist")]
    pub signer_does_not_exist: Box<models::InvalidTxErrorOneOf2SignerDoesNotExist>,
}

impl InvalidTxErrorOneOf2 {
    /// TX signer_id is not found in a storage
    pub fn new(signer_does_not_exist: models::InvalidTxErrorOneOf2SignerDoesNotExist) -> InvalidTxErrorOneOf2 {
        InvalidTxErrorOneOf2 {
            signer_does_not_exist: Box::new(signer_does_not_exist),
        }
    }
}

