/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf12 : The receiver shard of the transaction missed several chunks and rejects new transaction until it can make progress again.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf12 {
    #[serde(rename = "ShardStuck")]
    pub shard_stuck: Box<models::InvalidTxErrorOneOf12ShardStuck>,
}

impl InvalidTxErrorOneOf12 {
    /// The receiver shard of the transaction missed several chunks and rejects new transaction until it can make progress again.
    pub fn new(shard_stuck: models::InvalidTxErrorOneOf12ShardStuck) -> InvalidTxErrorOneOf12 {
        InvalidTxErrorOneOf12 {
            shard_stuck: Box::new(shard_stuck),
        }
    }
}

