/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf4 : Transaction nonce is larger than the upper bound given by the block height
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf4 {
    #[serde(rename = "NonceTooLarge")]
    pub nonce_too_large: Box<models::InvalidTxErrorOneOf4NonceTooLarge>,
}

impl InvalidTxErrorOneOf4 {
    /// Transaction nonce is larger than the upper bound given by the block height
    pub fn new(nonce_too_large: models::InvalidTxErrorOneOf4NonceTooLarge) -> InvalidTxErrorOneOf4 {
        InvalidTxErrorOneOf4 {
            nonce_too_large: Box::new(nonce_too_large),
        }
    }
}

