/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf5InvalidReceiverId {
    #[serde(rename = "receiver_id")]
    pub receiver_id: String,
}

impl InvalidTxErrorOneOf5InvalidReceiverId {
    pub fn new(receiver_id: String) -> InvalidTxErrorOneOf5InvalidReceiverId {
        InvalidTxErrorOneOf5InvalidReceiverId {
            receiver_id,
        }
    }
}

