/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf4NonceTooLarge {
    #[serde(rename = "tx_nonce")]
    pub tx_nonce: i32,
    #[serde(rename = "upper_bound")]
    pub upper_bound: i32,
}

impl InvalidTxErrorOneOf4NonceTooLarge {
    pub fn new(tx_nonce: i32, upper_bound: i32) -> InvalidTxErrorOneOf4NonceTooLarge {
        InvalidTxErrorOneOf4NonceTooLarge {
            tx_nonce,
            upper_bound,
        }
    }
}

