/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf8 : An error occurred while validating actions of a Transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf8 {
    #[serde(rename = "ActionsValidation")]
    pub actions_validation: Box<models::ActionsValidationError>,
}

impl InvalidTxErrorOneOf8 {
    /// An error occurred while validating actions of a Transaction.
    pub fn new(actions_validation: models::ActionsValidationError) -> InvalidTxErrorOneOf8 {
        InvalidTxErrorOneOf8 {
            actions_validation: Box::new(actions_validation),
        }
    }
}

