/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxError : An error happened during TX execution
/// An error happened during TX execution
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InvalidTxError {
    InvalidTxErrorOneOf(Box<models::InvalidTxErrorOneOf>),
    InvalidTxErrorOneOf1(Box<models::InvalidTxErrorOneOf1>),
    InvalidTxErrorOneOf2(Box<models::InvalidTxErrorOneOf2>),
    InvalidTxErrorOneOf3(Box<models::InvalidTxErrorOneOf3>),
    InvalidTxErrorOneOf4(Box<models::InvalidTxErrorOneOf4>),
    InvalidTxErrorOneOf5(Box<models::InvalidTxErrorOneOf5>),
    /// TX signature is not valid
    String(String),
    InvalidTxErrorOneOf6(Box<models::InvalidTxErrorOneOf6>),
    InvalidTxErrorOneOf7(Box<models::InvalidTxErrorOneOf7>),
    /// An integer overflow occurred during transaction cost estimation.
    String(String),
    /// Transaction parent block hash doesn't belong to the current chain
    String(String),
    /// Transaction has expired
    String(String),
    InvalidTxErrorOneOf8(Box<models::InvalidTxErrorOneOf8>),
    InvalidTxErrorOneOf9(Box<models::InvalidTxErrorOneOf9>),
    /// Transaction version is invalid.
    String(String),
    InvalidTxErrorOneOf10(Box<models::InvalidTxErrorOneOf10>),
    InvalidTxErrorOneOf11(Box<models::InvalidTxErrorOneOf11>),
    InvalidTxErrorOneOf12(Box<models::InvalidTxErrorOneOf12>),
}

impl Default for InvalidTxError {
    fn default() -> Self {
        Self::InvalidTxErrorOneOf(Default::default())
    }
}

