/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidAccessKeyErrorOneOf3 : Access Key does not have enough allowance to cover transaction cost
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidAccessKeyErrorOneOf3 {
    #[serde(rename = "NotEnoughAllowance")]
    pub not_enough_allowance: Box<models::InvalidAccessKeyErrorOneOf3NotEnoughAllowance>,
}

impl InvalidAccessKeyErrorOneOf3 {
    /// Access Key does not have enough allowance to cover transaction cost
    pub fn new(not_enough_allowance: models::InvalidAccessKeyErrorOneOf3NotEnoughAllowance) -> InvalidAccessKeyErrorOneOf3 {
        InvalidAccessKeyErrorOneOf3 {
            not_enough_allowance: Box::new(not_enough_allowance),
        }
    }
}

