/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf : Happens if a wrong AccessKey used or AccessKey has not enough permissions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf {
    #[serde(rename = "InvalidAccessKeyError")]
    pub invalid_access_key_error: Box<models::InvalidAccessKeyError>,
}

impl InvalidTxErrorOneOf {
    /// Happens if a wrong AccessKey used or AccessKey has not enough permissions
    pub fn new(invalid_access_key_error: models::InvalidAccessKeyError) -> InvalidTxErrorOneOf {
        InvalidTxErrorOneOf {
            invalid_access_key_error: Box::new(invalid_access_key_error),
        }
    }
}

