/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InvalidTxErrorOneOf3 : Transaction nonce must be `account[access_key].nonce + 1`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf3 {
    #[serde(rename = "InvalidNonce")]
    pub invalid_nonce: Box<models::InvalidTxErrorOneOf3InvalidNonce>,
}

impl InvalidTxErrorOneOf3 {
    /// Transaction nonce must be `account[access_key].nonce + 1`.
    pub fn new(invalid_nonce: models::InvalidTxErrorOneOf3InvalidNonce) -> InvalidTxErrorOneOf3 {
        InvalidTxErrorOneOf3 {
            invalid_nonce: Box::new(invalid_nonce),
        }
    }
}

