/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvalidTxErrorOneOf12ShardStuck {
    /// The shard that fails making progress.
    #[serde(rename = "shard_id")]
    pub shard_id: i32,
    /// The number of blocks since the last included chunk of the shard.
    #[serde(rename = "missed_chunks")]
    pub missed_chunks: i32,
}

impl InvalidTxErrorOneOf12ShardStuck {
    pub fn new(shard_id: i32, missed_chunks: i32) -> InvalidTxErrorOneOf12ShardStuck {
        InvalidTxErrorOneOf12ShardStuck {
            shard_id,
            missed_chunks,
        }
    }
}

