/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsonRpcResponse {
    #[serde(rename = "jsonrpc")]
    pub jsonrpc: String,
    #[serde(rename = "result")]
    pub result: Box<models::RpcTransactionResponse>,
    #[serde(rename = "id")]
    pub id: String,
}

impl JsonRpcResponse {
    pub fn new(jsonrpc: String, result: models::RpcTransactionResponse, id: String) -> JsonRpcResponse {
        JsonRpcResponse {
            jsonrpc,
            result: Box::new(result),
            id,
        }
    }
}

