/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MissingTrieValueContext : Contexts in which `StorageError::MissingTrieValue` error might occur.
/// Contexts in which `StorageError::MissingTrieValue` error might occur.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MissingTrieValueContext {
    /// Missing trie value when reading from TrieIterator.
    String(String),
    /// Missing trie value when reading from TriePrefetchingStorage.
    String(String),
    /// Missing trie value when reading from TrieMemoryPartialStorage.
    String(String),
    /// Missing trie value when reading from TrieStorage.
    String(String),
}

impl Default for MissingTrieValueContext {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

