/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrepareError : Error that can occur while preparing or executing Wasm smart-contract.
/// Error that can occur while preparing or executing Wasm smart-contract.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PrepareError {
    /// Error happened while serializing the module.
    String(String),
    /// Error happened while deserializing the module.
    String(String),
    /// Internal memory declaration has been found in the module.
    String(String),
    /// Gas instrumentation failed.  This most likely indicates the module isn't valid.
    String(String),
    /// Stack instrumentation failed.  This  most likely indicates the module isn't valid.
    String(String),
    /// Error happened during instantiation.  This might indicate that `start` function trapped, or module isn't instantiable and/or un-linkable.
    String(String),
    /// Error creating memory.
    String(String),
    /// Contract contains too many functions.
    String(String),
    /// Contract contains too many locals.
    String(String),
}

impl Default for PrepareError {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

