/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationErrorOneOf4 : The length of the returned data exceeded the limit in a DataReceipt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOf4 {
    #[serde(rename = "ReturnedValueLengthExceeded")]
    pub returned_value_length_exceeded: Box<models::HostErrorOneOf9KeyLengthExceeded>,
}

impl ReceiptValidationErrorOneOf4 {
    /// The length of the returned data exceeded the limit in a DataReceipt.
    pub fn new(returned_value_length_exceeded: models::HostErrorOneOf9KeyLengthExceeded) -> ReceiptValidationErrorOneOf4 {
        ReceiptValidationErrorOneOf4 {
            returned_value_length_exceeded: Box::new(returned_value_length_exceeded),
        }
    }
}

