/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationErrorOneOf6 : An error occurred while validating actions of an ActionReceipt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOf6 {
    #[serde(rename = "ActionsValidation")]
    pub actions_validation: Box<models::ActionsValidationError>,
}

impl ReceiptValidationErrorOneOf6 {
    /// An error occurred while validating actions of an ActionReceipt.
    pub fn new(actions_validation: models::ActionsValidationError) -> ReceiptValidationErrorOneOf6 {
        ReceiptValidationErrorOneOf6 {
            actions_validation: Box::new(actions_validation),
        }
    }
}

