/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationErrorOneOf5 : The number of input data dependencies exceeds the limit in an ActionReceipt.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOf5 {
    #[serde(rename = "NumberInputDataDependenciesExceeded")]
    pub number_input_data_dependencies_exceeded: Box<models::HostErrorOneOf13NumberInputDataDependenciesExceeded>,
}

impl ReceiptValidationErrorOneOf5 {
    /// The number of input data dependencies exceeds the limit in an ActionReceipt.
    pub fn new(number_input_data_dependencies_exceeded: models::HostErrorOneOf13NumberInputDataDependenciesExceeded) -> ReceiptValidationErrorOneOf5 {
        ReceiptValidationErrorOneOf5 {
            number_input_data_dependencies_exceeded: Box::new(number_input_data_dependencies_exceeded),
        }
    }
}

