/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOfInvalidPredecessorId {
    #[serde(rename = "account_id")]
    pub account_id: String,
}

impl ReceiptValidationErrorOneOfInvalidPredecessorId {
    pub fn new(account_id: String) -> ReceiptValidationErrorOneOfInvalidPredecessorId {
        ReceiptValidationErrorOneOfInvalidPredecessorId {
            account_id,
        }
    }
}

