/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationErrorOneOf7 : Receipt is bigger than the limit.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOf7 {
    #[serde(rename = "ReceiptSizeExceeded")]
    pub receipt_size_exceeded: Box<models::HostErrorOneOf15ContractSizeExceeded>,
}

impl ReceiptValidationErrorOneOf7 {
    /// Receipt is bigger than the limit.
    pub fn new(receipt_size_exceeded: models::HostErrorOneOf15ContractSizeExceeded) -> ReceiptValidationErrorOneOf7 {
        ReceiptValidationErrorOneOf7 {
            receipt_size_exceeded: Box::new(receipt_size_exceeded),
        }
    }
}

