/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationError : Describes the error for validating a receipt.
/// Describes the error for validating a receipt.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReceiptValidationError {
    ReceiptValidationErrorOneOf(Box<models::ReceiptValidationErrorOneOf>),
    ReceiptValidationErrorOneOf1(Box<models::ReceiptValidationErrorOneOf1>),
    ReceiptValidationErrorOneOf2(Box<models::ReceiptValidationErrorOneOf2>),
    ReceiptValidationErrorOneOf3(Box<models::ReceiptValidationErrorOneOf3>),
    ReceiptValidationErrorOneOf4(Box<models::ReceiptValidationErrorOneOf4>),
    ReceiptValidationErrorOneOf5(Box<models::ReceiptValidationErrorOneOf5>),
    ReceiptValidationErrorOneOf6(Box<models::ReceiptValidationErrorOneOf6>),
    ReceiptValidationErrorOneOf7(Box<models::ReceiptValidationErrorOneOf7>),
}

impl Default for ReceiptValidationError {
    fn default() -> Self {
        Self::ReceiptValidationErrorOneOf(Default::default())
    }
}

