/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationErrorOneOf3 : The `receiver_id` of a DataReceiver within an ActionReceipt is not valid.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOf3 {
    #[serde(rename = "InvalidDataReceiverId")]
    pub invalid_data_receiver_id: Box<models::ReceiptValidationErrorOneOfInvalidPredecessorId>,
}

impl ReceiptValidationErrorOneOf3 {
    /// The `receiver_id` of a DataReceiver within an ActionReceipt is not valid.
    pub fn new(invalid_data_receiver_id: models::ReceiptValidationErrorOneOfInvalidPredecessorId) -> ReceiptValidationErrorOneOf3 {
        ReceiptValidationErrorOneOf3 {
            invalid_data_receiver_id: Box::new(invalid_data_receiver_id),
        }
    }
}

