/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptEnumViewOneOf1 {
    #[serde(rename = "Data")]
    pub data: Box<models::ReceiptEnumViewOneOf1Data>,
}

impl ReceiptEnumViewOneOf1 {
    pub fn new(data: models::ReceiptEnumViewOneOf1Data) -> ReceiptEnumViewOneOf1 {
        ReceiptEnumViewOneOf1 {
            data: Box::new(data),
        }
    }
}

