/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReceiptValidationErrorOneOf2 : The `signer_id` of an ActionReceipt is not valid.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptValidationErrorOneOf2 {
    #[serde(rename = "InvalidSignerId")]
    pub invalid_signer_id: Box<models::ReceiptValidationErrorOneOfInvalidPredecessorId>,
}

impl ReceiptValidationErrorOneOf2 {
    /// The `signer_id` of an ActionReceipt is not valid.
    pub fn new(invalid_signer_id: models::ReceiptValidationErrorOneOfInvalidPredecessorId) -> ReceiptValidationErrorOneOf2 {
        ReceiptValidationErrorOneOf2 {
            invalid_signer_id: Box::new(invalid_signer_id),
        }
    }
}

