/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReceiptEnumView {
    ReceiptEnumViewOneOf(Box<models::ReceiptEnumViewOneOf>),
    ReceiptEnumViewOneOf1(Box<models::ReceiptEnumViewOneOf1>),
    ReceiptEnumViewOneOf2(Box<models::ReceiptEnumViewOneOf2>),
}

impl Default for ReceiptEnumView {
    fn default() -> Self {
        Self::ReceiptEnumViewOneOf(Default::default())
    }
}

