/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptEnumViewOneOf2GlobalContractDistribution {
    #[serde(rename = "data")]
    pub data: Box<models::GlobalContractData>,
}

impl ReceiptEnumViewOneOf2GlobalContractDistribution {
    pub fn new(data: models::GlobalContractData) -> ReceiptEnumViewOneOf2GlobalContractDistribution {
        ReceiptEnumViewOneOf2GlobalContractDistribution {
            data: Box::new(data),
        }
    }
}

