/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptEnumViewOneOf {
    #[serde(rename = "Action")]
    pub action: Box<models::ReceiptEnumViewOneOfAction>,
}

impl ReceiptEnumViewOneOf {
    pub fn new(action: models::ReceiptEnumViewOneOfAction) -> ReceiptEnumViewOneOf {
        ReceiptEnumViewOneOf {
            action: Box::new(action),
        }
    }
}

