/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RpcTransactionResponse {
    #[serde(rename = "final_execution_status")]
    pub final_execution_status: Box<models::TxExecutionStatus>,
    /// Receipts generated from the transaction
    #[serde(rename = "receipts")]
    pub receipts: Vec<models::ReceiptView>,
    /// Execution status defined by chain.rs:get_final_transaction_result FinalExecutionStatus::NotStarted - the tx is not converted to the receipt yet FinalExecutionStatus::Started - we have at least 1 receipt, but the first leaf receipt_id (using dfs) hasn't finished the execution FinalExecutionStatus::Failure - the result of the first leaf receipt_id FinalExecutionStatus::SuccessValue - the result of the first leaf receipt_id
    #[serde(rename = "status")]
    pub status: Box<models::FinalExecutionStatus>,
    /// Signed Transaction
    #[serde(rename = "transaction")]
    pub transaction: Box<models::SignedTransactionView>,
    /// The execution outcome of the signed transaction.
    #[serde(rename = "transaction_outcome")]
    pub transaction_outcome: Box<models::ExecutionOutcomeWithIdView>,
    /// The execution outcome of receipts.
    #[serde(rename = "receipts_outcome")]
    pub receipts_outcome: Vec<models::ExecutionOutcomeWithIdView>,
}

impl RpcTransactionResponse {
    pub fn new(final_execution_status: models::TxExecutionStatus, receipts: Vec<models::ReceiptView>, status: models::FinalExecutionStatus, transaction: models::SignedTransactionView, transaction_outcome: models::ExecutionOutcomeWithIdView, receipts_outcome: Vec<models::ExecutionOutcomeWithIdView>) -> RpcTransactionResponse {
        RpcTransactionResponse {
            final_execution_status: Box::new(final_execution_status),
            receipts,
            status: Box::new(status),
            transaction: Box::new(transaction),
            transaction_outcome: Box::new(transaction_outcome),
            receipts_outcome,
        }
    }
}

