/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignedDelegateAction {
    #[serde(rename = "delegate_action")]
    pub delegate_action: Box<models::DelegateAction>,
    #[serde(rename = "signature")]
    pub signature: String,
}

impl SignedDelegateAction {
    pub fn new(delegate_action: models::DelegateAction, signature: String) -> SignedDelegateAction {
        SignedDelegateAction {
            delegate_action: Box::new(delegate_action),
            signature,
        }
    }
}

