/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StakeAction : An action which stakes signer_id tokens and setup's validator public key
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakeAction {
    /// Amount of tokens to stake.
    #[serde(rename = "stake")]
    pub stake: String,
    /// Validator key which will be used to sign transactions on behalf of signer_id
    #[serde(rename = "public_key")]
    pub public_key: String,
}

impl StakeAction {
    /// An action which stakes signer_id tokens and setup's validator public key
    pub fn new(stake: String, public_key: String) -> StakeAction {
        StakeAction {
            stake,
            public_key,
        }
    }
}

