/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StorageErrorOneOf1 : Either invalid state or key-value db is corrupted. For PartialStorage it cannot be corrupted. Error message is unreliable and for debugging purposes only. It's also probably ok to panic in every place that produces this error. We can check if db is corrupted by verifying everything in the state trie.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageErrorOneOf1 {
    #[serde(rename = "StorageInconsistentState")]
    pub storage_inconsistent_state: String,
}

impl StorageErrorOneOf1 {
    /// Either invalid state or key-value db is corrupted. For PartialStorage it cannot be corrupted. Error message is unreliable and for debugging purposes only. It's also probably ok to panic in every place that produces this error. We can check if db is corrupted by verifying everything in the state trie.
    pub fn new(storage_inconsistent_state: String) -> StorageErrorOneOf1 {
        StorageErrorOneOf1 {
            storage_inconsistent_state,
        }
    }
}

