/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StorageError : Errors which may occur during working with trie storages, storing trie values (trie nodes and state values) by their hashes.
/// Errors which may occur during working with trie storages, storing trie values (trie nodes and state values) by their hashes.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StorageError {
    /// Key-value db internal failure
    String(String),
    StorageErrorOneOf(Box<models::StorageErrorOneOf>),
    /// Found trie node which shouldn't be part of state. Raised during validation of state sync parts where incorrect node was passed. TODO (#8997): consider including hash of trie node.
    String(String),
    StorageErrorOneOf1(Box<models::StorageErrorOneOf1>),
    StorageErrorOneOf2(Box<models::StorageErrorOneOf2>),
    StorageErrorOneOf3(Box<models::StorageErrorOneOf3>),
    /// Indicates that a resharding operation on flat storage is already in progress, when it wasn't expected to be so.
    String(String),
}

impl Default for StorageError {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

