/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StorageErrorOneOf : Requested trie value by its hash which is missing in storage.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageErrorOneOf {
    #[serde(rename = "MissingTrieValue")]
    pub missing_trie_value: String,
}

impl StorageErrorOneOf {
    /// Requested trie value by its hash which is missing in storage.
    pub fn new(missing_trie_value: String) -> StorageErrorOneOf {
        StorageErrorOneOf {
            missing_trie_value,
        }
    }
}

