/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StorageErrorOneOf3 : In-memory trie could not be loaded for some reason.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageErrorOneOf3 {
    #[serde(rename = "MemTrieLoadingError")]
    pub mem_trie_loading_error: String,
}

impl StorageErrorOneOf3 {
    /// In-memory trie could not be loaded for some reason.
    pub fn new(mem_trie_loading_error: String) -> StorageErrorOneOf3 {
        StorageErrorOneOf3 {
            mem_trie_loading_error,
        }
    }
}

