/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TxExecutionStatus {
    /// Transaction is waiting to be included into the block
    String(String),
    /// Transaction is included into the block. The block may be not finalized yet
    String(String),
    /// Transaction is included into the block + All non-refund transaction receipts finished their execution. The corresponding blocks for tx and each receipt may be not finalized yet
    String(String),
    /// Transaction is included into finalized block
    String(String),
    /// Transaction is included into finalized block + All non-refund transaction receipts finished their execution. The corresponding blocks for each receipt may be not finalized yet
    String(String),
    /// Transaction is included into finalized block + Execution of all transaction receipts is finalized, including refund receipts
    String(String),
}

impl Default for TxExecutionStatus {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

