/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UseGlobalContractAction : Use global contract action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UseGlobalContractAction {
    #[serde(rename = "contract_identifier")]
    pub contract_identifier: Box<models::GlobalContractIdentifier>,
}

impl UseGlobalContractAction {
    /// Use global contract action
    pub fn new(contract_identifier: models::GlobalContractIdentifier) -> UseGlobalContractAction {
        UseGlobalContractAction {
            contract_identifier: Box::new(contract_identifier),
        }
    }
}

