/*
 * okapirocket
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WasmTrap : A kind of a trap happened during execution of a binary
/// A kind of a trap happened during execution of a binary
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WasmTrap {
    /// An `unreachable` opcode was executed.
    String(String),
    /// Call indirect incorrect signature trap.
    String(String),
    /// Memory out of bounds trap.
    String(String),
    /// Call indirect out of bounds trap.
    String(String),
    /// An arithmetic exception, e.g. divided by zero.
    String(String),
    /// Misaligned atomic access trap.
    String(String),
    /// Indirect call to null.
    String(String),
    /// Stack overflow.
    String(String),
    /// Generic trap.
    String(String),
}

impl Default for WasmTrap {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

