[package]
name = "codeprogen"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
progenitor = { path = "../../../progenitor/progenitor" }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
